In [1]:
import torch 
import torch.nn as nn 
import numpy as np 
import matplotlib.pyplot as plt 
import time

I'm using my base anaconda environment for this notebook, as opposed to the python runtimes I usually use for my other notebooks.

# NumPy vs Torch

Numpy **arrays** and PyTorch **tensors** are similar in many ways. They both are n-dimensional arrays, and they both support a large number of operations. However, there are some important differences between them. 

In [2]:
n = np.linspace(0, 1, 5)
t = torch.linspace(0, 1, 5)

In [3]:
n

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
t

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

They can be resized very similarly. 

In [5]:
n = np.arange(48).reshape(3, 4, 4)
t = torch.arange(48).reshape(3, 4, 4)

They have the same broadcasting rules.

# General Broadcasting Rules

**NumPy** compares the shape of the two arrays element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when 

1. they are equal, or
2. one of them is 1

**Example**: The following arrays are compatible for broadcasting:

    Shape1: (1, 6, 4, 1, 7, 2)
    Shape2: (5, 6, 1, 3, 1, 2)

Notice the numbers in parentheses are not actual elements of the array, but rather the shape of the array (they're both 6-dimensional arrays). The trailing dimensions are compatible because they are equal. The next two dimensions are compatible because one of them is 1. 
Going forward and checking element-wise, the two arrays are compatible for broadcasting.
    

    
    

    
    

In [7]:
a = np.array([1, 2])
b = np.array([3, 4])
a * b

array([3, 8])

In [10]:
a = np.ones((6, 5))
b = np.arange(5).reshape((1, 5))

array([[0, 1, 2, 3, 4]])

In [12]:
print(a.shape)
print(b.shape)

(6, 5)
(1, 5)


They're compatible! The trailing dimensions are equal, and the next two dimensions are compatible because one of them is 1.

In [11]:
a + b

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

$b$ has been broadcasted to match the shape of $a$, notice how it has been added elementwise and for each of the 5 rows.

All these examples work the same way using PyTorch tensors.

**Example**: Scaling each of the color channels of an image by a different amount 

        Image  (3D array): 256 x 256 x 3
        Scale  (1D array):             3
        Result (3D array): 256 x 256 x 3

In [13]:
Image = torch.randn((256, 256, 3))
Scale = torch.tensor([0.5, 1.5, 1])

In [14]:
Result = Image * Scale

Each pixel has its own RGB value and the scale array is broadcasted by automatically "filling" the missing dimensions with 1, which is compatible with the 3D array, as we saw above.

In [16]:
Result

tensor([[[-0.4851,  0.6219,  1.1986],
         [-0.5104, -0.1032, -1.1994],
         [-0.2464,  0.9703,  0.2011],
         ...,
         [ 0.0038, -0.6432,  0.5227],
         [ 0.2252, -1.7203,  0.7954],
         [-1.4113, -1.5692,  0.3791]],

        [[-0.1975, -2.2298,  0.0923],
         [-0.2060,  1.7708, -0.7949],
         [-0.1571, -2.8495, -1.2338],
         ...,
         [-0.1112,  0.9085, -0.2579],
         [-0.1972,  0.7657, -2.3204],
         [-0.3097,  3.6715,  0.0459]],

        [[ 0.4238,  2.5619,  1.1865],
         [-0.1382, -0.4225, -0.1328],
         [-0.2797, -0.6732,  0.3435],
         ...,
         [ 0.1257, -2.3191,  1.0249],
         [-0.2588, -0.7808,  0.1031],
         [-0.3322,  0.2506,  1.8672]],

        ...,

        [[ 0.5494, -2.5491,  0.0916],
         [ 0.0252, -0.0083, -0.7250],
         [ 0.0184, -1.0566, -1.0034],
         ...,
         [ 0.2031,  0.8488, -1.8105],
         [ 0.4318, -0.8357,  0.8961],
         [-0.3683, -0.8883,  1.5579]],

        [[